name: CI-CD

on: 
  push: 
    branches: ["main"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.1.0
      
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.2.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            californibrs/live-kube-news:${{github.run_number}}
            californibrs/live-kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
      - uses: actions/checkout@v3.1.0
      
      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image 
        run: | 
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          make build-image
          echo -n "verifying images:"
          docker images

      - name: Deploy to minikube
        run: 
          kubectl apply -f k8s/deployment.yaml
      - name: Test service URLs
        run: | 
          minikube service list
          minikube service discover --url
          echo -n "------------------opening the service------------------"
          curl $(minikube service discover --url)/version
